# Generated by Django 2.0.13 on 2019-03-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190325_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='price',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='cash',
            field=models.CharField(default='0', max_length=25),
            preserve_default=False,
        ),
    ]
