# Generated by Django 2.0.13 on 2019-03-25 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190325_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='country',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='game.country'),
            preserve_default=False,
        ),
    ]
