# Generated by Django 2.0.13 on 2019-03-25 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_player_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='country',
            field=models.ForeignKey(default='USA', on_delete=django.db.models.deletion.CASCADE, to='game.country'),
        ),
    ]
