# Generated by Django 2.0.13 on 2019-03-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20190325_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='inventory',
            field=models.IntegerField(default=25),
        ),
    ]
