# Generated by Django 2.0.13 on 2019-05-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_player_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='debt',
            field=models.CharField(default='2000', max_length=25),
        ),
        migrations.AddField(
            model_name='player',
            name='health',
            field=models.CharField(default='100', max_length=25),
        ),
        migrations.AlterField(
            model_name='country',
            name='country',
            field=models.CharField(default='USA', max_length=25),
        ),
        migrations.AlterField(
            model_name='player',
            name='cash',
            field=models.CharField(default='2000', max_length=25),
        ),
    ]
