# Generated by Django 2.0.13 on 2019-05-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20190503_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='house',
            field=models.CharField(default='Homeless', max_length=50),
        ),
    ]
