# Generated by Django 2.0.13 on 2019-05-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.CharField(default='none', max_length=250),
        ),
    ]
