# Generated by Django 2.0.13 on 2019-05-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_house_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='owned',
            field=models.BooleanField(default='False'),
        ),
    ]
